import '../styles/globals.css'
import styles from '../styles/Home.module.css'
import Link from "next/link"
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  
  return (
  <>
   <Head>
        <title>Next js tut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* Script tag can add to this line */}
      </Head>
 
    <Component {...pageProps} />
  </>
    )
}

export default MyApp
