import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link"
export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Next js tut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* Script tag can add to this line */}
      </Head>

      <nav className={styles.navbar}>
        <ul>
          <li>
          <Link href="/about">Home</Link>
           </li>
          <li>
            
          <Link href="/about">About</Link></li>
          <li>

          <Link href="/service">Service</Link>
          </li>
          <li>
          <Link href="/contact"> Contact</Link>
            </li>
        </ul>
      </nav>
   
    </div>
  )
}
